// setup-env - existsSync helper and configureEnv - Deno-only
// - uses Deno-filesystem and prompt for env setup - no npm
import { isWin, join } from './runners.ts'
import { loadEnv } from './reset.ts'
export function existsSync(path: string): boolean {
	try {
		Deno.statSync(path)
		return true
	} catch {
		return false
	}
}
// 2 - Configure Environment
export function configureEnv(_rl: any) {
	console.log('\n=========================================')
	console.log('       Configuration Wizard              ')
	console.log('=========================================')

	// Read locale directory to find available languages
	const localesDir = join('locale')
	let languages: string[] = ['pt', 'en', 'es', 'fr', 'de']
	try {
		if (existsSync(localesDir)) {
			const files = Array.from(Deno.readDirSync(localesDir)).map((f) => f.name)
			languages = files.filter((f) => f.endsWith('.json')).map((f) =>
				f.replace(/\.json$/, '')
			)
		}
	} catch (_e) {
		// Keep defaults
	}

	// Choose language
	console.log('\nAvailable Bot Languages:')
	languages.forEach((lang, idx) => {
		console.log(`  [${idx + 1}] ${lang}`)
	})
	const langChoice = prompt(`Choose language [1-${languages.length}] (default: pt): `)
	const selectedLang = languages[parseInt(langChoice || '1') - 1] || 'pt'

	// Choose Prefix
	const prefix = prompt('\nEnter Bot Command Prefix (default: .): ') || '.'

	// Timezone
	const timezones = [
		'America/Sao_Paulo',
		'UTC',
		'America/New_York',
		'Europe/London',
		'Asia/Tokyo',
	]
	console.log('\nCommon Timezones:')
	timezones.forEach((tz, idx) => {
		console.log(`  [${idx + 1}] ${tz}`)
	})
	console.log(`  [${timezones.length + 1}] Custom Timezone`)
	const tzChoiceInput = prompt(
		`Choose timezone [1-${timezones.length + 1}] (default: America/Sao_Paulo): `,
	)
	let selectedTz = 'America/Sao_Paulo'
	const tzChoice = parseInt(tzChoiceInput || '1')
	if (tzChoice > 0 && tzChoice <= timezones.length) {
		selectedTz = timezones[tzChoice - 1]
	} else if (tzChoice === timezones.length + 1) {
		selectedTz = prompt('Enter custom timezone (e.g. Europe/Paris, UTC): ') ||
			'America/Sao_Paulo'
	}

	// Database URL
	const dbUrl = prompt(
		'\nEnter Database URL (optional, PostgreSQL recommended. Press enter to skip): ',
	)

	// Developers
	const devsInput = prompt(
		'\nEnter Developer Phone numbers / LIDs separated by a comma (optional. Press enter to skip): ',
	)
	const selectedDevs = devsInput
		? devsInput.split(',').map((s) => s.trim()).filter(Boolean).join('|')
		: ''

	// Gemini Key
	const geminiKey = prompt(
		'\nEnter Gemini API Key (optional. Press enter to skip. get a key on https://aistudio.google.com/app/apikey): ',
	)

	// Ensure conf folder exists
	if (!existsSync('conf')) {
		Deno.mkdirSync('conf', { recursive: true })
	}

	// Write .env (preserve unknown keys such as bridge config)
	const envPath = join('conf', '.env')
	const existingEnv = new Map<string, string>()
	if (existsSync(envPath)) {
		for (const line of Deno.readTextFileSync(envPath).split('\n')) {
			const trimmed = line.trim()
			if (!trimmed || trimmed.startsWith('#')) continue
			const idx = trimmed.indexOf('=')
			if (idx > 0) {
				existingEnv.set(trimmed.substring(0, idx).trim(), trimmed.substring(idx + 1))
			}
		}
	}
	const esc = (v: string | null) => `'${(v ?? '').replace(/'/g, `'"'"'`)}'`
	const nextEnv = new Map(existingEnv)
	nextEnv.set('TZ', esc(selectedTz))
	if (dbUrl) nextEnv.set('DATABASE_URL', esc(dbUrl))
	if (devsInput !== null) nextEnv.set('DEVS', esc(selectedDevs))
	if (geminiKey) nextEnv.set('GEMINI', esc(geminiKey))
	if (!nextEnv.has('GROUPS1')) nextEnv.set('GROUPS1', `''`)
	if (!nextEnv.has('GROUPS2')) nextEnv.set('GROUPS2', `''`)
	const envContent = `# Generated by Ergon WA Bot Setup Wizard\n` +
		[...nextEnv.entries()].map(([k, v]) => `${k}=${v}`).join('\n') + '\n'
	Deno.writeTextFileSync(envPath, envContent)
	console.log(`\nWritten configuration to ${envPath} (bridge keys preserved)`)

	// Write/Update defaults.json
	const defaultsPath = join('conf', 'defaults.json')
	let defaults: any = {}
	if (existsSync(defaultsPath)) {
		try {
			defaults = JSON.parse(Deno.readTextFileSync(defaultsPath))
		} catch (_e) {
			console.warn('Could not parse existing defaults.json. Recreating...')
		}
	}

	defaults.lang = selectedLang
	defaults.prefix = prefix

	// Ensure runner configuration uses correct cross-platform pathing
	if (!defaults.runner) defaults.runner = {}
	if (isWin) {
		defaults.runner.ytdlp = 'conf/gen/python/Scripts/yt-dlp'
		if (!defaults.runner.py) defaults.runner.py = {}
		defaults.runner.py.cmd = ['conf/gen/python/Scripts/python']
	} else {
		defaults.runner.ytdlp = 'conf/gen/python/bin/yt-dlp'
		if (!defaults.runner.py) defaults.runner.py = {}
		defaults.runner.py.cmd = ['conf/gen/python/bin/python3']
	}

	Deno.writeTextFileSync(defaultsPath, JSON.stringify(defaults, null, '\t') + '\n')
	console.log(`Updated defaults.json language, prefix, and platform paths.`)

	// Load the env variables into the process
	loadEnv()
}
